local wk = require("which-key")

wk.add(
  {
    { "<leader>X",         desc = "Close all buffers except current" },
    { "<leader>a",         desc = "Add to harpoon" },
    { "<leader>d",         desc = "Deleting to void register" },
    { "<leader>e",         "<cmd>Telescope find_files<cr>",          desc = "Find File" },
    { "<leader>f",         group = "Telescope" },
    { "<leader>f<leader>", "<cmd>Telescope resume<cr>",              desc = "resume" },
    { "<leader>fW",        "<cmd>Telescope grep_string<cr>",         desc = "Current (W)ord" },
    { "<leader>fb",        "<cmd>Telescope buffers<cr>",             desc = "(b)uffer" },
    { "<leader>fe",        "<cmd>Telescope find_files<cr>",          desc = "fil(e)" },
    { "<leader>ff",        "<cmd>Telescope find_files<cr>",          desc = "(f)ile" },
    { "<leader>fg",        "<cmd>Telescope git_files<cr>",           desc = "(g)it file" },
    { "<leader>fh",        "<cmd>Telescope oldfiles<cr>",            desc = "(h)istory" },
    { "<leader>fw",        "<cmd>Telescope live_grep<cr>",           desc = "(w)ord" },
    { "<leader>pp",        desc = "Paste without yanking" },
    { "<leader>q",         desc = "Close quicklist" },
    { "<leader>s",         group = "Replace current word" },
    { "<leader>s$",        desc = "Line" },
    { "<leader>sG",        group = "To end of file" },
    { "<leader>sGG",       desc = "To end of file" },
    { "<leader>sGc",       desc = "To end of file (confirm)" },
    { "<leader>sc",        desc = "Global (confirm)" },
    { "<leader>ss",        desc = "Global" },
    { "<leader>tt",        desc = "Copy relative path" },
    { "<leader>u",         desc = "Undotree" },
    { "<leader>vw",        group = "Workspace" },
    { "<leader>vws",       desc = "Workspace symbol" },
    { "<leader>x",         desc = "Close current buffer" },
    { "<leader>y",         desc = "Copy in OS yank" },
    { "<leader>z",         desc = "Zen mode" },
  })
